services:
  backend:
    build:
      context: ./Reprecord.Backend
      dockerfile: Dockerfile
    depends_on:
      - dynamodb-local
    networks:
      - local-dynamodb
    ports:
      - "3000-3003:3000-3003"
    environment:
      NODE_ENV: "localdevelopment"
    volumes:
      - ./Reprecord.Backend:/app
      - /app/node_modules
    command: npm run start:docker

  dynamodb-local:
    image: amazon/dynamodb-local:latest
    networks:
      - local-dynamodb
    ports:
      - "8000:8000"
    environment:
      - JAVA_OPTS=-Xms512m -Xmx1g
    volumes:
      - ./Reprecord.Backend/dynamodb-data:/home/dynamodblocal/data
    command: "-jar DynamoDBLocal.jar -sharedDb -dbPath /home/dynamodblocal/data"

networks:
  local-dynamodb:
