user_pool_name = "reprecord-pool-DEV"
domain_name    = "reprecordd"
client_name    = "reprecord-client-dev"
callback_url   = "http://localhost:3000/federatedLogin"
logout_url     = "http://localhost:3000/logged_out"
