environment    = "production"
user_pool_name = "reprecord-pool"
domain_name    = "reprecord"
client_name    = "reprecord-client"
callback_url   = "https://reprecord.onrender.com/federatedLogin"
logout_url     = "https://reprecord.onrender.com/logged_out"
