user_pool_name = "reprecord-pool-QAS"
domain_name    = "reprecordq"
client_name    = "reprecord-client-qas"
callback_url   = "https://localhost:3000/logged_in"
logout_url     = "https://localhost:3000/logged_out"
