user_pool_name = "reprecord-pool-QAS"
domain_name    = "reprecordq"
client_name    = "reprecord-client-qas"
callback_url   = "http://localhost:3000/federatedLogin"
logout_url     = "http://localhost:3000/logged_out"
