environment    = "qas"
user_pool_name = "reprecord-pool-QAS"
domain_name    = "reprecordq"
client_name    = "reprecord-client-qas"
callback_url   = "https://reprecord-xiys.onrender.com/federatedLogin"
logout_url     = "https://reprecord-xiys.onrender.com/logged_out"
