name: Deploy Infra to AWS

on:
  push:
    branches:
      - master
  workflow_dispatch: # Enable manual runs

jobs:
  deploy-infra:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        environment: [dev] #, QAS, PRD]

    environment: ${{ matrix.environment }}
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v3

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v4
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: us-east-2

    - name: Initialize Terraform
      run: terraform init -backend-config="key=${{ matrix.environment }}/terraform.tfstate" 
      working-directory: ./Reprecord.Backend/Terraform

    - name: Apply Terraform
      env:
        TF_VAR_google_client_id: '${{ secrets.GOOGLE_CLIENT_ID }}'
        TF_VAR_google_client_secret: '${{ secrets.GOOGLE_CLIENT_SECRET }}'
      run: terraform apply -auto-approve -var-file=var/${{ matrix.environment }}.tfvars
      working-directory: ./Reprecord.Backend/Terraform