name: Deploy Infra to AWS

on:
  push:
    branches:
      - master
  workflow_dispatch: # Enable manual runs

jobs:
  deploy:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        environment: [dev] #, QAS, PRD]

    environment: ${{ matrix.environment }}
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v1
      with:
        terraform_version: 1.0.0

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: us-east-2
    
    - name: Initialize Terraform
      run: terraform init \
            -backend-config="hostname=app.terraform.io" \
            -backend-config="organization=Personal-yhshan" \
            -backend-config="workspaces{name=reprecord-${{ matrix.environment }}}"
      working-directory: ./Reprecord.Backend/Terraform

    - name: Configure Terraform Cloud Credentials
      env:
        TFE_TOKEN: ${{ secrets.TF_CLOUD_TOKEN }}
      run: terraform login

    - name: Apply Terraform
      env:
        TF_VAR_google_client_id: '${{ secrets.GOOGLE_CLIENT_ID }}'
        TF_VAR_google_client_secret: '${{ secrets.GOOGLE_CLIENT_SECRET }}'
      run: terraform apply -auto-approve -var-file=var/${{ matrix.environment }}.tfvars
      working-directory: ./Reprecord.Backend/Terraform